### ISSUE TITLE
Unrecognized launcher type: prebuilt

### ISSUE THREAD

**Issue by perok** [coursier/setup-action#171]
Hi!

We just started seeing the following failure in CI:

![image](https://user-images.githubusercontent.com/1502013/152117064-7a0904fb-20db-485a-b779-cb0a66503ecf.png)

Might it be related to https://github.com/coursier/apps/pull/134? Upgrade to setup-action@v1.2.0-M2 solves it :)

**Comment by ihostage** [comment]
Also related to #163. `v1` tag is outdated and if maintainers will re-push them to the latest stable, it's going to fix many related problems where to use `coursier/setup-action@v1`.

**Comment by alexarchambault** [comment]
It should have gone better since https://github.com/coursier/apps/pull/135, merged and released a few hours ago.

**Comment by alexarchambault** [comment]
Else, you can just switch to a setup-action milestone, like `1.2.0-M2`.

**Comment by laughedelic** [comment]
@perok is this still an issue with the latest version of the action?

**Comment by perok** [comment]
No, it's working fine now. Thanks! I can close the issue.
