### ISSUE TITLE
Consider using Disco API instead of Jabba

### ISSUE THREAD

**Issue by sideeffffect** [coursier/setup-action#220]
Consider using the Disco API for all the metadata about Java distributions, vendors, platforms, URLs, etc.
https://github.com/foojay2020/discoapi

Jabba is not kept up to date. ( https://github.com/coursier/jvm-index is currently being used, but then we wouldn't need to maintain it.)
EDIT: Jabba seems to be dead https://github.com/shyiko/jabba/issues/833

**Comment by alexarchambault** [comment]
Closing in favor of https://github.com/coursier/coursier/issues/2057.
